11.18 solve slack format message issues

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -36,10 +36,15 @@ jobs:
         if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
         run: |
           flyctl deploy --remote-only
-          APP_URL=$(flyctl status --json | jq -r '.Hostname')
+          if APP_URL=$(flyctl status --json | jq -r '.Hostname'); then
+            echo "APP_URL=${APP_URL}" >> "$GITHUB_ENV"
+            echo "${APP_URL}"
+          else
+            echo "Failed to get APP_URL"
+            exit 1
+          fi
         env: 
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
-          APP_URL: $APP_URL
       - name: Deployment Job Successful
         if: ${{ success() && github.event_name == 'push' }}
         id: slack
@@ -58,7 +63,7 @@ jobs:
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "${{ env.APP_URL }}"
+                        "text": "$APP_URL"
                       }
                     }
                   ]
